version: "2.2"

services:
  backend_service:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: fast_api_container
    ports:
      - "8000:8000"

  frontend_service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_container
    ports:
      - "4200:4200"
