name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Check Docker version
      - name: Check Docker version
        run: docker --version

      # Log in to Harbor Docker Registry
      - name: Log in to Harbor
        run: echo "${{ secrets.OWNER_PASS }}" | docker login harbor.druid.moe -u "${{ secrets.OWNER_NAME }}" --password-stdin

      # Build and Push Docker images
      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: harbor.druid.moe/boardmeetings/backend:0.1.1
          
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: harbor.druid.moe/boardmeetings/front:0.1.1
